# Generated by Django 4.0 on 2022-02-17 17:36

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_images_image_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=25, size=[500, 300], upload_to='thumbnail/'),
        ),
    ]
